[2024-01-19T09:54:06.798+0000] {processor.py:161} INFO - Started process (PID=29) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T09:54:06.806+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T09:54:06.884+0000] {logging_mixin.py:188} INFO - [2024-01-19T09:54:06.867+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T09:54:06.971+0000] {logging_mixin.py:188} INFO - [2024-01-19T09:54:06.954+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index=0, os.path.os.path.dirname(os.path.abspath(__file__)))
                                                                                 ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T09:54:06.976+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T09:54:08.191+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 1.581 seconds
[2024-01-19T09:54:38.944+0000] {processor.py:161} INFO - Started process (PID=30) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T09:54:39.148+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T09:54:39.162+0000] {logging_mixin.py:188} INFO - [2024-01-19T09:54:39.157+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T09:54:39.256+0000] {logging_mixin.py:188} INFO - [2024-01-19T09:54:39.252+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index=0, os.path.os.path.dirname(os.path.abspath(__file__)))
                                                                                 ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T09:54:39.258+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T09:54:39.420+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.518 seconds
[2024-01-19T09:55:09.977+0000] {processor.py:161} INFO - Started process (PID=31) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T09:55:09.979+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T09:55:09.984+0000] {logging_mixin.py:188} INFO - [2024-01-19T09:55:09.982+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T09:55:10.022+0000] {logging_mixin.py:188} INFO - [2024-01-19T09:55:10.018+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index=0, os.path.os.path.dirname(os.path.abspath(__file__)))
                                                                                 ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T09:55:10.029+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T09:55:10.112+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.154 seconds
[2024-01-19T09:55:40.693+0000] {processor.py:161} INFO - Started process (PID=32) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T09:55:40.697+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T09:55:40.704+0000] {logging_mixin.py:188} INFO - [2024-01-19T09:55:40.702+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T09:55:40.755+0000] {logging_mixin.py:188} INFO - [2024-01-19T09:55:40.751+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index=0, os.path.os.path.dirname(os.path.abspath(__file__)))
                                                                                 ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T09:55:40.759+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T09:55:40.840+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.165 seconds
[2024-01-19T09:56:11.206+0000] {processor.py:161} INFO - Started process (PID=33) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T09:56:11.214+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T09:56:11.221+0000] {logging_mixin.py:188} INFO - [2024-01-19T09:56:11.220+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T09:56:11.273+0000] {logging_mixin.py:188} INFO - [2024-01-19T09:56:11.270+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index=0, os.path.os.path.dirname(os.path.abspath(__file__)))
                                                                                 ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T09:56:11.276+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T09:56:11.402+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.208 seconds
[2024-01-19T09:56:41.742+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T09:56:41.747+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T09:56:41.760+0000] {logging_mixin.py:188} INFO - [2024-01-19T09:56:41.759+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T09:56:41.825+0000] {logging_mixin.py:188} INFO - [2024-01-19T09:56:41.815+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index=0, os.path.os.path.dirname(os.path.abspath(__file__)))
                                                                                 ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T09:56:41.829+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T09:56:41.920+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.186 seconds
[2024-01-19T09:57:12.157+0000] {processor.py:161} INFO - Started process (PID=35) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T09:57:12.163+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T09:57:12.166+0000] {logging_mixin.py:188} INFO - [2024-01-19T09:57:12.165+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T09:57:12.195+0000] {logging_mixin.py:188} INFO - [2024-01-19T09:57:12.193+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index=0, os.path.os.path.dirname(os.path.abspath(__file__)))
                                                                                 ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T09:57:12.196+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T09:57:12.269+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.117 seconds
[2024-01-19T09:57:42.670+0000] {processor.py:161} INFO - Started process (PID=36) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T09:57:42.677+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T09:57:42.770+0000] {logging_mixin.py:188} INFO - [2024-01-19T09:57:42.768+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T09:57:42.916+0000] {logging_mixin.py:188} INFO - [2024-01-19T09:57:42.913+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index=0, os.path.os.path.dirname(os.path.abspath(__file__)))
                                                                                 ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T09:57:42.918+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T09:57:43.009+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.384 seconds
[2024-01-19T09:58:13.209+0000] {processor.py:161} INFO - Started process (PID=37) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T09:58:13.218+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T09:58:13.227+0000] {logging_mixin.py:188} INFO - [2024-01-19T09:58:13.221+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T09:58:13.247+0000] {logging_mixin.py:188} INFO - [2024-01-19T09:58:13.246+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index=0, os.path.os.path.dirname(os.path.abspath(__file__)))
                                                                                 ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T09:58:13.248+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T09:58:13.328+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.129 seconds
[2024-01-19T09:58:43.442+0000] {processor.py:161} INFO - Started process (PID=38) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T09:58:43.446+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T09:58:43.463+0000] {logging_mixin.py:188} INFO - [2024-01-19T09:58:43.462+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T09:58:43.491+0000] {logging_mixin.py:188} INFO - [2024-01-19T09:58:43.488+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index=0, os.path.os.path.dirname(os.path.abspath(__file__)))
                                                                                 ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T09:58:43.493+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T09:58:43.559+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.128 seconds
[2024-01-19T09:59:13.940+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T09:59:13.949+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T09:59:13.953+0000] {logging_mixin.py:188} INFO - [2024-01-19T09:59:13.952+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T09:59:14.012+0000] {logging_mixin.py:188} INFO - [2024-01-19T09:59:14.009+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index=0, os.path.os.path.dirname(os.path.abspath(__file__)))
                                                                                 ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T09:59:14.014+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T09:59:14.103+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.173 seconds
[2024-01-19T09:59:44.490+0000] {processor.py:161} INFO - Started process (PID=40) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T09:59:44.494+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T09:59:44.502+0000] {logging_mixin.py:188} INFO - [2024-01-19T09:59:44.499+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T09:59:44.558+0000] {logging_mixin.py:188} INFO - [2024-01-19T09:59:44.555+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index=0, os.path.os.path.dirname(os.path.abspath(__file__)))
                                                                                 ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T09:59:44.564+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T09:59:44.652+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.187 seconds
[2024-01-19T10:00:14.815+0000] {processor.py:161} INFO - Started process (PID=41) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:00:14.818+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:00:14.823+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:00:14.822+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:00:14.861+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:00:14.850+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index=0, os.path.os.path.dirname(os.path.abspath(__file__)))
                                                                                 ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:00:14.865+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:00:14.958+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.157 seconds
[2024-01-19T10:00:45.213+0000] {processor.py:161} INFO - Started process (PID=42) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:00:45.217+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:00:45.220+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:00:45.219+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:00:45.237+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:00:45.236+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index=0, os.path.os.path.dirname(os.path.abspath(__file__)))
                                                                                 ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:00:45.238+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:00:45.283+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.079 seconds
[2024-01-19T10:01:15.572+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:01:15.576+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:01:15.583+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:01:15.582+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:01:15.605+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:01:15.603+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index=0, os.path.os.path.dirname(os.path.abspath(__file__)))
                                                                                 ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:01:15.606+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:01:15.647+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.085 seconds
[2024-01-19T10:01:45.845+0000] {processor.py:161} INFO - Started process (PID=44) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:01:45.848+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:01:45.853+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:01:45.852+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:01:45.875+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:01:45.871+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index=0, os.path.os.path.dirname(os.path.abspath(__file__)))
                                                                                 ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:01:45.876+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:01:45.909+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.071 seconds
[2024-01-19T10:02:16.331+0000] {processor.py:161} INFO - Started process (PID=45) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:02:16.341+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:02:16.349+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:02:16.349+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:02:16.372+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:02:16.371+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index=0, os.path.os.path.dirname(os.path.abspath(__file__)))
                                                                                 ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:02:16.372+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:02:16.407+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.081 seconds
[2024-01-19T10:02:46.767+0000] {processor.py:161} INFO - Started process (PID=46) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:02:46.769+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:02:46.774+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:02:46.773+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:02:46.791+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:02:46.790+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 6
    sys.path.insert(__index=0, os.path.os.path.dirname(os.path.abspath(__file__)))
                                                                                 ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:02:46.791+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:02:46.829+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.067 seconds
[2024-01-19T10:02:52.907+0000] {processor.py:161} INFO - Started process (PID=47) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:02:52.910+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:02:52.916+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:02:52.915+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:02:52.959+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:02:52.958+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:02:52.960+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:02:53.015+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.116 seconds
[2024-01-19T10:03:23.237+0000] {processor.py:161} INFO - Started process (PID=48) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:03:23.241+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:03:23.246+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:03:23.245+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:03:23.269+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:03:23.268+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:03:23.272+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:03:23.316+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.091 seconds
[2024-01-19T10:03:53.747+0000] {processor.py:161} INFO - Started process (PID=49) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:03:53.748+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:03:53.751+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:03:53.750+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:03:53.772+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:03:53.771+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:03:53.773+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:03:53.798+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.054 seconds
[2024-01-19T10:04:24.173+0000] {processor.py:161} INFO - Started process (PID=50) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:04:24.176+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:04:24.180+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:04:24.180+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:04:24.216+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:04:24.215+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:04:24.217+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:04:24.261+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.092 seconds
[2024-01-19T10:04:54.492+0000] {processor.py:161} INFO - Started process (PID=51) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:04:54.494+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:04:54.498+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:04:54.497+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:04:54.526+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:04:54.524+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:04:54.527+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:04:54.562+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.075 seconds
[2024-01-19T10:05:24.928+0000] {processor.py:161} INFO - Started process (PID=52) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:05:24.930+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:05:24.932+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:05:24.932+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:05:24.959+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:05:24.958+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:05:24.960+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:05:24.989+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.067 seconds
[2024-01-19T10:05:55.377+0000] {processor.py:161} INFO - Started process (PID=53) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:05:55.380+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:05:55.382+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:05:55.381+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:05:55.398+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:05:55.397+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:05:55.399+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:05:55.420+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.047 seconds
[2024-01-19T10:06:25.829+0000] {processor.py:161} INFO - Started process (PID=54) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:06:25.838+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:06:25.844+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:06:25.843+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:06:25.881+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:06:25.878+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:06:25.883+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:06:25.936+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.121 seconds
[2024-01-19T10:06:56.171+0000] {processor.py:161} INFO - Started process (PID=55) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:06:56.172+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:06:56.176+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:06:56.175+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:06:56.195+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:06:56.194+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:06:56.196+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:06:56.227+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.063 seconds
[2024-01-19T10:07:26.574+0000] {processor.py:161} INFO - Started process (PID=56) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:07:26.576+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:07:26.580+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:07:26.579+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:07:26.599+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:07:26.597+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:07:26.601+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:07:26.644+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.080 seconds
[2024-01-19T10:07:57.007+0000] {processor.py:161} INFO - Started process (PID=57) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:07:57.009+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:07:57.011+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:07:57.010+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:07:57.030+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:07:57.029+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:07:57.030+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:07:57.093+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.089 seconds
[2024-01-19T10:08:27.372+0000] {processor.py:161} INFO - Started process (PID=58) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:08:27.374+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:08:27.377+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:08:27.376+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:08:27.402+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:08:27.400+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:08:27.403+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:08:27.466+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.098 seconds
[2024-01-19T10:08:57.813+0000] {processor.py:161} INFO - Started process (PID=59) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:08:57.814+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:08:57.816+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:08:57.816+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:08:57.835+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:08:57.834+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:08:57.835+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:08:57.868+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.059 seconds
[2024-01-19T10:09:28.331+0000] {processor.py:161} INFO - Started process (PID=60) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:09:28.332+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:09:28.334+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:09:28.334+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:09:28.352+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:09:28.351+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:09:28.352+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:09:28.376+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.049 seconds
[2024-01-19T10:09:58.754+0000] {processor.py:161} INFO - Started process (PID=61) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:09:58.755+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:09:58.758+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:09:58.758+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:09:58.776+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:09:58.775+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:09:58.777+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:09:58.801+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.051 seconds
[2024-01-19T10:10:29.222+0000] {processor.py:161} INFO - Started process (PID=62) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:10:29.223+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:10:29.227+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:10:29.226+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:10:29.253+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:10:29.252+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:10:29.254+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:10:29.293+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.078 seconds
[2024-01-19T10:10:59.643+0000] {processor.py:161} INFO - Started process (PID=63) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:10:59.645+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:10:59.651+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:10:59.649+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:10:59.714+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:10:59.705+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:10:59.716+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:10:59.827+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.195 seconds
[2024-01-19T10:11:30.030+0000] {processor.py:161} INFO - Started process (PID=64) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:11:30.031+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:11:30.034+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:11:30.033+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:11:30.061+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:11:30.060+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:11:30.062+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:11:30.151+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.125 seconds
[2024-01-19T10:12:00.487+0000] {processor.py:161} INFO - Started process (PID=65) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:12:00.489+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:12:00.492+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:12:00.492+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:12:00.517+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:12:00.516+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:12:00.518+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:12:00.544+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.064 seconds
[2024-01-19T10:12:30.918+0000] {processor.py:161} INFO - Started process (PID=66) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:12:30.920+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:12:30.922+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:12:30.922+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:12:30.941+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:12:30.940+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:12:30.942+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:12:30.966+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.053 seconds
[2024-01-19T10:13:01.352+0000] {processor.py:161} INFO - Started process (PID=67) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:13:01.353+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:13:01.356+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:13:01.356+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:13:01.375+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:13:01.374+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:13:01.375+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:13:01.401+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.052 seconds
[2024-01-19T10:13:31.703+0000] {processor.py:161} INFO - Started process (PID=68) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:13:31.706+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:13:31.710+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:13:31.709+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:13:31.734+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:13:31.733+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:13:31.734+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:13:31.771+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.072 seconds
[2024-01-19T10:14:02.162+0000] {processor.py:161} INFO - Started process (PID=69) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:14:02.164+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:14:02.169+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:14:02.169+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:14:02.197+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:14:02.196+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:14:02.198+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:14:02.232+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.082 seconds
[2024-01-19T10:14:32.627+0000] {processor.py:161} INFO - Started process (PID=70) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:14:32.628+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:14:32.631+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:14:32.631+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:14:32.654+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:14:32.653+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:14:32.654+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:14:32.679+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.056 seconds
[2024-01-19T10:15:03.019+0000] {processor.py:161} INFO - Started process (PID=71) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:15:03.021+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:15:03.023+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:15:03.023+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:15:03.041+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:15:03.040+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:15:03.041+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:15:03.065+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.049 seconds
[2024-01-19T10:15:33.449+0000] {processor.py:161} INFO - Started process (PID=72) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:15:33.450+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:15:33.453+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:15:33.452+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:15:33.485+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:15:33.484+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:15:33.487+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:15:33.523+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.080 seconds
[2024-01-19T10:16:03.869+0000] {processor.py:161} INFO - Started process (PID=73) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:16:03.871+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:16:03.873+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:16:03.873+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:16:03.912+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:16:03.910+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:16:03.913+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:16:03.961+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.096 seconds
[2024-01-19T10:16:34.290+0000] {processor.py:161} INFO - Started process (PID=74) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:16:34.292+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:16:34.294+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:16:34.294+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:16:34.316+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:16:34.315+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:16:34.317+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:16:34.348+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.064 seconds
[2024-01-19T10:17:04.682+0000] {processor.py:161} INFO - Started process (PID=75) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:17:04.683+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:17:04.687+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:17:04.686+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:17:04.712+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:17:04.711+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:17:04.713+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:17:04.762+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.085 seconds
[2024-01-19T10:17:35.152+0000] {processor.py:161} INFO - Started process (PID=76) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:17:35.153+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:17:35.156+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:17:35.156+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:17:35.185+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:17:35.184+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:17:35.186+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:17:35.218+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.075 seconds
[2024-01-19T10:18:05.536+0000] {processor.py:161} INFO - Started process (PID=77) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:18:05.537+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:18:05.540+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:18:05.540+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:18:05.561+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:18:05.561+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:18:05.562+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:18:05.587+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.055 seconds
[2024-01-19T10:18:35.930+0000] {processor.py:161} INFO - Started process (PID=78) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:18:35.931+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:18:35.934+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:18:35.933+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:18:35.953+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:18:35.952+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:18:35.953+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:18:35.976+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.049 seconds
[2024-01-19T10:19:06.485+0000] {processor.py:161} INFO - Started process (PID=79) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:19:06.486+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:19:06.489+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:19:06.489+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:19:06.513+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:19:06.512+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:19:06.514+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:19:06.545+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.063 seconds
[2024-01-19T10:19:36.854+0000] {processor.py:161} INFO - Started process (PID=80) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:19:36.856+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:19:36.858+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:19:36.858+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:19:36.893+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:19:36.892+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:19:36.895+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:19:36.934+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.084 seconds
[2024-01-19T10:20:07.358+0000] {processor.py:161} INFO - Started process (PID=81) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:20:07.359+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:20:07.362+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:20:07.362+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:20:07.382+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:20:07.381+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:20:07.382+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:20:07.410+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.056 seconds
[2024-01-19T10:20:37.784+0000] {processor.py:161} INFO - Started process (PID=82) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:20:37.785+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:20:37.789+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:20:37.789+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:20:37.810+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:20:37.809+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:20:37.811+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:20:37.842+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.061 seconds
[2024-01-19T10:21:08.184+0000] {processor.py:161} INFO - Started process (PID=83) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:21:08.188+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:21:08.191+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:21:08.191+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:21:08.227+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:21:08.226+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:21:08.229+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:21:08.275+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.101 seconds
[2024-01-19T10:21:38.640+0000] {processor.py:161} INFO - Started process (PID=84) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:21:38.641+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:21:38.643+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:21:38.643+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:21:38.704+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:21:38.702+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:21:38.705+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:21:38.858+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.223 seconds
[2024-01-19T10:22:09.148+0000] {processor.py:161} INFO - Started process (PID=85) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:22:09.149+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:22:09.152+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:22:09.151+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:22:09.175+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:22:09.174+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:22:09.176+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:22:09.204+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.060 seconds
[2024-01-19T10:22:39.637+0000] {processor.py:161} INFO - Started process (PID=86) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:22:39.639+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:22:39.646+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:22:39.645+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:22:39.670+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:22:39.668+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:22:39.670+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:22:39.700+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.067 seconds
[2024-01-19T10:23:10.115+0000] {processor.py:161} INFO - Started process (PID=87) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:23:10.118+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:23:10.121+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:23:10.121+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:23:10.143+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:23:10.142+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:23:10.145+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:23:10.169+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.057 seconds
[2024-01-19T10:23:40.577+0000] {processor.py:161} INFO - Started process (PID=88) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:23:40.578+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:23:40.581+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:23:40.581+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:23:40.605+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:23:40.603+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:23:40.606+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:23:40.642+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.069 seconds
[2024-01-19T10:24:10.919+0000] {processor.py:161} INFO - Started process (PID=89) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:24:10.921+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:24:10.924+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:24:10.924+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:24:10.949+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:24:10.947+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:24:10.949+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:24:10.978+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.063 seconds
[2024-01-19T10:24:41.302+0000] {processor.py:161} INFO - Started process (PID=90) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:24:41.304+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:24:41.307+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:24:41.306+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:24:41.329+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:24:41.328+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:24:41.330+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:24:41.358+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.060 seconds
[2024-01-19T10:25:11.608+0000] {processor.py:161} INFO - Started process (PID=91) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:25:11.609+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:25:11.611+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:25:11.611+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:25:11.636+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:25:11.635+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:25:11.636+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:25:11.660+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.056 seconds
[2024-01-19T10:25:41.906+0000] {processor.py:161} INFO - Started process (PID=92) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:25:41.908+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:25:41.910+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:25:41.910+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:25:41.929+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:25:41.928+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:25:41.929+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:25:41.961+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.061 seconds
[2024-01-19T10:26:12.117+0000] {processor.py:161} INFO - Started process (PID=93) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:26:12.119+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:26:12.121+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:26:12.121+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:26:12.140+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:26:12.139+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:26:12.141+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:26:12.166+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.054 seconds
[2024-01-19T10:26:42.426+0000] {processor.py:161} INFO - Started process (PID=94) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:26:42.427+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:26:42.430+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:26:42.429+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:26:42.449+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:26:42.447+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:26:42.450+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:26:42.474+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.052 seconds
[2024-01-19T10:27:12.658+0000] {processor.py:161} INFO - Started process (PID=95) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:27:12.661+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:27:12.665+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:27:12.664+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:27:12.691+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:27:12.690+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:27:12.692+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:27:12.728+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.076 seconds
[2024-01-19T10:27:42.963+0000] {processor.py:161} INFO - Started process (PID=96) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:27:42.966+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:27:42.969+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:27:42.969+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:27:42.997+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:27:42.996+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:27:42.998+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:27:43.027+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.068 seconds
[2024-01-19T10:28:13.316+0000] {processor.py:161} INFO - Started process (PID=97) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:28:13.317+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:28:13.320+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:28:13.319+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:28:13.341+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:28:13.340+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:28:13.342+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:28:13.367+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.057 seconds
[2024-01-19T10:28:43.605+0000] {processor.py:161} INFO - Started process (PID=98) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:28:43.606+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:28:43.609+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:28:43.608+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:28:43.629+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:28:43.626+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:28:43.630+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:28:43.659+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.058 seconds
[2024-01-19T10:29:13.892+0000] {processor.py:161} INFO - Started process (PID=99) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:29:13.896+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:29:13.902+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:29:13.901+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:29:13.933+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:29:13.930+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:29:13.934+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:29:13.974+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.085 seconds
[2024-01-19T10:29:44.133+0000] {processor.py:161} INFO - Started process (PID=100) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:29:44.135+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:29:44.139+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:29:44.138+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:29:44.171+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:29:44.170+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:29:44.172+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:29:44.201+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.076 seconds
[2024-01-19T10:30:14.351+0000] {processor.py:161} INFO - Started process (PID=101) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:30:14.353+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:30:14.355+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:30:14.355+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:30:14.376+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:30:14.375+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:30:14.377+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:30:14.404+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.059 seconds
[2024-01-19T10:30:44.589+0000] {processor.py:161} INFO - Started process (PID=102) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:30:44.590+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:30:44.595+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:30:44.594+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:30:44.624+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:30:44.623+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:30:44.625+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:30:44.670+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.088 seconds
[2024-01-19T10:31:14.987+0000] {processor.py:161} INFO - Started process (PID=103) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:31:15.001+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:31:15.029+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:31:15.023+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:31:15.080+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:31:15.079+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:31:15.081+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:31:15.163+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.219 seconds
[2024-01-19T10:31:45.317+0000] {processor.py:161} INFO - Started process (PID=104) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:31:45.338+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:31:45.377+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:31:45.374+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:31:45.446+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:31:45.417+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:31:45.461+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:31:46.010+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.741 seconds
[2024-01-19T10:33:19.328+0000] {processor.py:161} INFO - Started process (PID=29) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:33:19.360+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:33:19.474+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:33:19.473+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:33:19.534+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:33:19.515+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:33:19.537+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:33:19.704+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.446 seconds
[2024-01-19T10:33:51.115+0000] {processor.py:161} INFO - Started process (PID=30) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:33:51.125+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:33:51.197+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:33:51.193+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:33:51.339+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:33:51.328+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:33:51.341+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:33:51.592+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.522 seconds
[2024-01-19T10:34:22.801+0000] {processor.py:161} INFO - Started process (PID=31) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:34:22.902+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:34:23.070+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:34:23.049+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:34:23.396+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:34:23.344+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:34:23.402+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:34:24.868+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 2.296 seconds
[2024-01-19T10:34:55.618+0000] {processor.py:161} INFO - Started process (PID=32) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:34:55.622+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:34:55.633+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:34:55.631+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:34:55.700+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:34:55.694+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:34:55.703+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:34:55.905+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.309 seconds
[2024-01-19T10:35:26.251+0000] {processor.py:161} INFO - Started process (PID=33) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:35:26.258+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:35:26.265+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:35:26.264+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:35:26.552+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:35:26.549+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:35:26.556+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:35:26.775+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.550 seconds
[2024-01-19T10:35:56.995+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:35:57.009+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:35:57.022+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:35:57.015+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:35:57.075+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:35:57.073+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:35:57.078+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:35:57.216+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.253 seconds
[2024-01-19T10:36:27.810+0000] {processor.py:161} INFO - Started process (PID=35) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:36:27.813+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:36:27.817+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:36:27.817+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:36:27.846+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:36:27.845+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:36:27.850+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:36:27.949+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.146 seconds
[2024-01-19T10:36:58.213+0000] {processor.py:161} INFO - Started process (PID=36) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:36:58.238+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:36:58.342+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:36:58.324+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:36:58.440+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:36:58.423+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:36:58.459+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:36:58.823+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.701 seconds
[2024-01-19T10:37:29.254+0000] {processor.py:161} INFO - Started process (PID=37) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:37:29.264+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:37:29.272+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:37:29.272+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:37:29.294+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:37:29.292+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:37:29.302+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:37:29.459+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.232 seconds
[2024-01-19T10:37:59.677+0000] {processor.py:161} INFO - Started process (PID=38) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:37:59.680+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:37:59.688+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:37:59.687+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:37:59.717+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:37:59.715+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:37:59.718+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:37:59.848+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.178 seconds
[2024-01-19T10:38:30.052+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:38:30.054+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:38:30.094+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:38:30.062+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:38:30.242+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:38:30.215+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:38:30.244+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:38:30.714+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.700 seconds
[2024-01-19T10:39:01.140+0000] {processor.py:161} INFO - Started process (PID=40) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:39:01.148+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:39:01.166+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:39:01.156+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:39:01.235+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:39:01.230+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:39:01.240+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:39:01.339+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.228 seconds
[2024-01-19T10:39:31.677+0000] {processor.py:161} INFO - Started process (PID=41) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:39:31.733+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:39:31.790+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:39:31.738+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:39:31.859+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:39:31.856+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:39:31.860+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:39:32.126+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.466 seconds
[2024-01-19T10:40:02.290+0000] {processor.py:161} INFO - Started process (PID=42) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:40:02.296+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:40:02.301+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:40:02.300+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:40:02.358+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:40:02.355+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:40:02.360+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:40:02.456+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.178 seconds
[2024-01-19T10:40:32.623+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:40:32.668+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:40:32.670+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:40:32.670+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:40:32.689+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:40:32.688+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:40:32.690+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:40:32.918+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.298 seconds
[2024-01-19T10:41:03.549+0000] {processor.py:161} INFO - Started process (PID=44) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:41:03.570+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:41:03.576+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:41:03.576+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:41:03.636+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:41:03.628+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:41:03.641+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:41:03.908+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.370 seconds
[2024-01-19T10:41:35.965+0000] {processor.py:161} INFO - Started process (PID=45) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:41:36.011+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:41:36.024+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:41:36.022+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:41:36.047+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:41:36.044+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:41:36.048+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:41:36.096+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.541 seconds
[2024-01-19T10:42:06.376+0000] {processor.py:161} INFO - Started process (PID=46) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:42:06.385+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:42:06.388+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:42:06.388+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:42:06.411+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:42:06.405+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:42:06.412+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:42:06.657+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.290 seconds
[2024-01-19T10:42:36.857+0000] {processor.py:161} INFO - Started process (PID=47) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:42:36.863+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:42:36.865+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:42:36.865+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:42:36.901+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:42:36.888+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:42:36.902+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:42:37.376+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.523 seconds
[2024-01-19T10:43:07.751+0000] {processor.py:161} INFO - Started process (PID=48) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:43:07.766+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:43:07.786+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:43:07.769+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:43:07.837+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:43:07.836+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:43:07.837+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:43:07.970+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.253 seconds
[2024-01-19T10:43:38.315+0000] {processor.py:161} INFO - Started process (PID=49) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:43:38.322+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:43:38.333+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:43:38.328+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:43:38.391+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:43:38.387+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:43:38.394+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:43:38.513+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.215 seconds
[2024-01-19T10:44:08.659+0000] {processor.py:161} INFO - Started process (PID=50) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:44:08.662+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:44:08.673+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:44:08.673+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:44:08.712+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:44:08.710+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:44:08.714+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:44:08.788+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.146 seconds
[2024-01-19T10:44:39.035+0000] {processor.py:161} INFO - Started process (PID=51) to work on /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:44:39.036+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2024-01-19T10:44:39.039+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:44:39.038+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:44:39.055+0000] {logging_mixin.py:188} INFO - [2024-01-19T10:44:39.054+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 8
    sys.path.insert(__index=0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                                                                                          ^
SyntaxError: positional argument follows keyword argument
[2024-01-19T10:44:39.056+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2024-01-19T10:44:39.081+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.050 seconds
